---
- name: Install Docker and Nginx
    apt:
      name:
        - docker.io
        - nginx
      state: present

- name: Make sure docker and Nginx are running and enabled
    systemd:
      name: docker
      state: started
      enabled: true

    systemd:
      name: nginx
      state: started
      enabled: true