---
- name: Deploy Jenkins container with Nginx proxy using Docker
  hosts: 34.203.13.70
  become: true

  tasks:
    - name: Install Docker and Nginx
      apt:
        name:
          - docker.io
          - nginx
        state: present

    - name: Start Docker and enable on boot
      systemd:
        name: docker
        state: started
        enabled: true

    - name: Start Nginx and enable on boot
      systemd:
        name: nginx
        state: started
        enabled: true

    - name: Start Jenkins container
      docker_container:
        name: jenkins
        image: jenkins/jenkins:lts
        state: started
        ports:
          - "8080:8080"

  handlers:
    - name: Restart Nginx
      systemd:
        name: nginx
        state: restarted