- name: Deploy Git, Docker, and Docker Compose
  hosts: all
  become: yes
  tasks:
    - name: Update apt repository and cache
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    - name: Install Git, Docker, and Compose
      apt:
        name:
          - git
          - docker-compose
          - docker.io
          - nginx
        state: present

#  roles:
#    - nginx
#    - jenkins

- name: Make sure docker is running and enabled
  hosts: all
  tasks:
    - systemd:
        name: docker
        state: started
        enabled: true

- name: Make sure Nginx is running and enabled
  hosts: all
  tasks:
    - systemd:
        name: nginx
        state: started
        enabled: true

# Next run the script for configuring nginx to proxy our app over ssl

- name: Copy nginx config scriptfile to remote server
  hosts: all
  tasks:
    - copy:
        src: /home/rolly/LS-Exam/.Server_Deployment/Ansible/roles/nginx/tls-config
        dest: /home/ubuntu
#        remote_user: ubuntu

- name: Make the script executable
  hosts: all
  become: yes
  tasks:
    - shell: chmod +x /home/rolly/LS-Exam/.Server_Deployment/Ansible/roles/nginx/conf-nginx.sh

- name: Execute the local script on remote server
  hosts: all
  become: yes
  tasks:
    - script: /home/rolly/LS-Exam/.Server_Deployment/Ansible/roles/nginx/conf-nginx.sh
