---
- name: Deploy Jenkins container with Nginx proxy using Docker
  hosts: all
  become: true

#  roles:
#  - nginx
# - jenkins

- tasks:

  - name: Install Docker and Nginx
    hosts: all
    apt:
        name:
          - docker.io
          - nginx
        state: present

  - name: Make sure docker is running and enabled
    hosts: all
    systemd:
      name: docker
      state: started
      enabled: true 

  - name: Make sure Nginx is running and enabled
    hosts: all
    systemd:
      name: nginx
      state: started
      enabled: true

# Next run the script for configuring nginx to proxy our app over ssl

  - name: Copy nginx config scriptfile to remote server
    hosts: all
    copy:
      src: /home/rolly/.Server_Deployment/Ansible/roles/nginx/tls-config
      dest: /home/ubuntu
      remote_user: ubuntu
      become: yes

  - name: Make the script executable
    hosts: all
    shell: chmod +x /home/rolly/.Server_Deployment/Ansible/roles/nginx/conf-nginx.sh

  - name: Execute the local script
    hosts: all
    script: /home/rolly/.Server_Deployment/Ansible/roles/nginx/conf-nginx.sh
