# using nginx 1.23.3 base image.
FROM nginx:1.23.3

# copy the index file which is part of the repo to replace the default nginx page.
COPY index.html /usr/share/nginx/html

# port for communication.
EXPOSE 80
