---
- name: Install Docker and Nginx
  apt:
      name:
        - docker.io
        - nginx
      state: present

- name: Make sure docker is running and enabled
  systemd:
    name: docker
    state: started
    enabled: true 

- name: Make sure Nginx is running and enabled
  systemd:
    name: nginx
    state: started
    enabled: true