vpc_cidr_bloc = "10.0.0.0/16"
subnet_cidr_block = "10.0.1.0/24"
avail_zone = "us-east-1e"
env_prefix = "LS-Exam"
myip_address = "0.0.0.0/0"
public_key_location = "/home/rolly/.ssh/ls-exam.pub"
private_key_location = "/home/rolly/.ssh/ls-exam"
ssh-user = "ubuntu"
ansible-script = "/home/rolly/LS-Exam/.Jenkins_Deployment/Ansible/config.yaml"
ansible_host_file = "/home/rolly/LS-Exam/.Jenkins_Deployment/Ansible/hosts"

