vpc_cidr_bloc = "10.0.0.0/16"
subnet_cidr_block = "10.0.10.0/24"
avail_zone = "us-east-2a"
env_prefix = "dev"
myip_address = "212.102.61.153/32"
public_key_location = "/home/rolly/.ssh/id_rsa.pub"
private_key_location = "/home/rolly/.ssh/id_rsa"
ssh-user = "ubuntu"
ansible-script = "/home/rolly/LS-Exam/.Jenkins_Deployment/Ansible/config.yaml"
ansible_host_file = "/home/rolly/LS-Exam/.Jenkins_Deployment/Ansible/hosts"

