---
- name: Install Docker and Nginx
    apt:
      name:
        - docker.io
        - nginx
      state: present

- name: Start Jenkins container
  docker_container:
    name: jenkins
      image: jenkins/jenkins:lts
      state: started
      ports:
        - "8080:8080"