name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build the application's Docker image
      run: docker build -t rp1sne22/ls-exam-image ./html_app

    - name: Run container
      run: docker run -d -p 80:80 rp1sne22/ls-exam-image   

    - name: Test Application
      run: curl --max-time 10 http://localhost

    - name: Login to Docker Hub
      run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKERHUB_PASSWD}}

    - name: Tag Image
      run: |
        docker tag rp1sne22/ls-exam-image rp1sne22/ls-exam-image:latest
        docker tag rp1sne22/ls-exam-image rp1sne22/ls-exam-image:$(git rev-parse --short ${{ github.sha }})

    - name: Push to Image to Docker Hub
      run: | 
        docker push rp1sne22/ls-exam-image:latest
        docker push rp1sne22/ls-exam-image:$(git rev-parse --short ${{ github.sha }})
        echo "image pushed successfully to artifact repository>>>"
    