name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build the application's Docker image
      run: docker build -t samsonidowu/ls-exam-image:$(date +'%Y-%m-%d') ./html_app

    - name: Run container
      run: docker run -d -p 80:80 samsonidowu/ls-exam-image:$(date +'%Y-%m-%d')   

    - name: Test Application
      run: curl --max-time 10 http://localhost
           echo test successful

