name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  

  build:

    steps:
    - uses: actions/checkout@v3
    - name: Build the application's Docker image
      run: docker build ./html_app -t ls-exam-image:$(date +%s)

  test:

    steps:
    - uses: actions/checkout@v3
    - name: Run and Test container
      run: docker run -d -p 80:80 --name ls-exam-app ls-exam-image:$(date +%s)
           curl http://localhost
           echo test successful

runs-on: ubuntu-latest